apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy25
  labels:
    app: autodeploy25
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718790220732
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy25
  template:
    metadata:
      labels:
        app: autodeploy25
    spec:
      containers:
        - name: autodeploy25
          image: acrworkflow1718790220732.azurecr.io/image-workflow-1718790220732:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
