apiVersion: v1
kind: Service
metadata:
  name: autodeploy25
  namespace: namespace-workflow-1718790220732
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy25
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000